### ISSUE TITLE
Get returns nothing when TTL set

### ISSUE THREAD

**Issue by PawelJ-PL** [cb372/scalacache#522] opened 2021-04-30 22:08 UTC
Hi,

It looks, that it's impossible to get value with `CaffeineCache`, if it was inserted with TTL.

Sample code:

```scala
import cats.effect.{ExitCode, IO, IOApp}
import scalacache.caffeine.CaffeineCache
import scalacache.{Cache, get, put}

object Main extends IOApp {
  val cache: IO[CaffeineCache[IO, String]] = CaffeineCache[IO, String]

  private def testCache(implicit c: Cache[IO, String]): IO[Unit] = for {
  _ <- put("foo")("bar", Some(scala.concurrent.duration.FiniteDuration(10, "days")))
  result <- get("foo")
  _ <- IO(println(result))
  } yield ()

  override def run(args: List[String]): IO[ExitCode] = cache.flatMap(implicit c => testCache.map(_ => ExitCode.Success))
}
```

It prints `None` but it should be `Some(bar)`. If I remove TTL, it works fine. My suspicion is that the following condition can be incorrect: https://github.com/cb372/scalacache/blob/1fb5879310a316553609ba4b026bb9089788eea7/modules/caffeine/src/main/scala/scalacache/caffeine/CaffeineCache.scala#L34

**Comment by PawelJ-PL** [comment] 2021-04-30 22:50
The updated code confirms my suspicions. The value is only available after it expires.

```scala
import cats.effect.{ExitCode, IO, IOApp}
import scalacache.caffeine.CaffeineCache
import scalacache.{Cache, get, put}

object Main extends IOApp {
  val cache: IO[CaffeineCache[IO, String]] = CaffeineCache[IO, String]

  private def testCache(implicit c: Cache[IO, String]): IO[Unit] = for {
  _ <- put("foo")("bar", Some(scala.concurrent.duration.FiniteDuration(7, "seconds")))
  result <- get("foo")
  _ <- IO(println(result))
  _ <- IO(Thread.sleep(10000))
  result2 <- get("foo")
  _ <- IO(println(result2))
  } yield ()

  override def run(args: List[String]): IO[ExitCode] = cache.flatMap(implicit c => testCache.map(_ => ExitCode.Success))
}
```

**Comment by Qi77Qi** [comment] 2021-09-08 21:07
Hi, I think I'm running into similar issue.

Here's a snippet to reproduce

```
import com.github.benmanes.caffeine.cache.Caffeine
import scala.concurrent.duration._

val underlyingCache = Caffeine.newBuilder().build[String, scalacache.Entry[String]]()
val cache: CaffeineCache[IO, String] = CaffeineCache[IO, String](underlyingCache)

val cacheWithTtl = cache.cachingF("keyTtl")(Some(1 hour))(IO(println("fetching value")).as("v1"))

scala> cacheWithTtl.unsafeRunSync
                    ^
       warning: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method unsafeRunSync,
       or remove the empty argument list from its definition (Java-defined methods are exempt).
       In Scala 3, an unapplied method like this will be eta-expanded into a function.
fetching value
val res9: String = v1

scala> cacheWithTtl.unsafeRunSync
                    ^
       warning: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method unsafeRunSync,
       or remove the empty argument list from its definition (Java-defined methods are exempt).
       In Scala 3, an unapplied method like this will be eta-expanded into a function.
fetching value
val res10: String = v1

scala> underlyingCache.asMap()
val res11: java.util.concurrent.ConcurrentMap[String,scalacache.Entry[String]] = {k1=Entry(v1,None), keyTtl=Entry(v1,Some(1970-01-08T02:23:22.244Z))}
```

Note "fetching value" gets printed out twice, which means the function is run twice to fetch the value. I think it's because expiration isn't set properly, somehow expiresAt is `1970-01-08T02:23:22.244Z` when ttl is set. If I don't set ttl, then expiresAt is set to `None`, and cache behavior is correct.

**Comment by kubukoz** [comment] 2021-09-09 00:53
Might be related to the CE3 migration. I'll look at it when I have a sec

**Comment by PawelJ-PL** [comment] 2021-09-09 07:11
I think my problem would be resolved by PR https://github.com/cb372/scalacache/pull/562.

Regarding date `1970` it's probably because, that cache is using montonic time, but it should't cause any problems.

**Comment by kubukoz** [comment] 2021-09-09 13:35
Merged #562, should be published soon in https://github.com/cb372/scalacache/actions/runs/1217511186

@PawelJ-PL if you can check that snapshot (might need to add a Sonatype snaphots resolver) and let me know it's working for you, I'll publish another milestone :)

**Comment by PawelJ-PL** [comment] 2021-09-09 14:04
With version `1.0.0-M4+18-e1b730d9-SNAPSHOT` it always returns `None` (after and before expirtation) :/

**Comment by kubukoz** [comment] 2021-09-09 14:41
Gonna play around with it some more, then

**Comment by ben-manes** [comment] 2021-09-09 15:55
Caffeine has native support for variable expiration and the `put(key, value, duration)` method. This is available in `cache.policy().expiresVariably()`. It requires configuring with `expiresAfter(Expiry)`, which could default to an infinite duration. It would be nice if as much as possible is delegated to the cache provider since it can implement functionality in a more efficient and tested manner (same with memoization).

**Comment by PawelJ-PL** [comment] 2021-09-09 16:24
I started using this approach when I came across this bug (and incidentally discovered that scalacache does not delete expired entries but only filters them out)

**Comment by kubukoz** [comment] 2021-09-21 15:36
I'll take a PR that moves to the caffeine-native expiration methods, unless I remember to take care of it myself when I have a few moments 😅

**Comment by yurique** [comment] 2021-09-23 22:05
https://github.com/cb372/scalacache/pull/562/files:
```scala
clock.realTimeInstant.map(_.isBefore(expiration))
```

expiration in monotonic time, `realTimeInstant` will never be "isBefore"

**Comment by kubukoz** [comment] 2021-09-23 22:40
Caught up on the caffeine API...

> If the cache was not constructed with variable expiration or the implementation does not support these operations, an empty Optional is returned.

@ben-manes I'm not a Caffeine user, do you know how likely it is that a user-provided cache would fall into that case? (forcing us to fall back to our own expiration mechanism)

In the meantime, I'll just use `realTimeInstant` everywhere.

**Comment by yurique** [comment] 2021-09-23 22:42
BTW the `Entry` class with the monotonic/realtime mix up is not caffeine specific. It's in core.
I tried to fix it in the PR above.

**Comment by ben-manes** [comment] 2021-09-23 23:00
It could be quite common as users decide what features to enable at construction. That dictates what data structures are allocated and the work to perform. There is no requirement for any policy (size, time, reference), so accepting a raw `Cache` leaves it unknown. It is rare for a local cache to ever use an explicit `put` rather than a memoizing loader, so most users never touch `cache.policy()` for feature-specific apis.

I suspect that ScalaCache tried to abstract away too many concepts (local, remote, memoization, expiration, vendor agnostic, etc). In this case you were coerced into reinventing the feature for your API, and at best redirect to an optimized wrapper if the expiration support was enabled on the cache. Of potential interest is the opposite approach of simply making Caffeine idiomatic in Scala as done in this [library](https://github.com/blemale/scaffeine).

**Closed** 2021-09-24 00:17 UTC
